services:
  shlink:
    image: shlinkio/shlink:stable
    restart: always
    environment:
      - TZ=${TZ:-Europe/Paris}
      - DEFAULT_DOMAIN=${DEFAULT_DOMAIN:-localhost}
      - IS_HTTPS_ENABLED=true
      - GEOLITE_LICENSE_KEY=${GEOLITE_LICENSE_KEY:-}
      - DB_DRIVER=${DB_DRIVER:-maria}
      - DB_USER=${DB_USER:-shlink}
      - DB_NAME=${DB_NAME:-shlink}
      - DB_PASSWORD=${DB_PASSWORD:-shlink}
      - DB_HOST=database
    depends_on:
      - database
    ports:
      - 8090:8080

  database:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root_password1234}
      - MARIADB_DATABASE=${DB_NAME:-shlink}
      - MARIADB_USER=${DB_USER:-shlink}
      - MARIADB_PASSWORD=${DB_PASSWORD:-shlink}
    volumes:
      - /srv/docker/shlink/db_data:/var/lib/mysql

  shlink-web-client:
    image: shlinkio/shlink-web-client
    restart: always
    container_name: shlink-gui
    volumes:
      - /srv/docker/shlink/nginx/servers.json:/usr/share/nginx/html/servers.json
    depends_on:
      - shlink
    ports:
      - 8334:8080
