version: '3.3'
services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    hostname: dkr-stirlingpdf-01
    ports:
      - '8033:8080'
    volumes:
      - /srv/docker/stirlingpdf/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - /srv/docker/stirlingpdf/extraConfigs:/configs
      - /srv/docker/stirlingpdf/customFiles:/customFiles/
      - /srv/docker/stirlingpdf/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=fr_FR