all:
  vars:
    domain: sevenos.fr
    ansible_user: root
    node_exporter_mount_points_exclude: '^/(proc($|/)|sys($|/)|run($|/)|tmp($|/)|mnt($|/)|media($|/)|dev($|/(pts|hugepages|mqueue))|var/lib/docker($|/)|var/lib/containers($|/)|var/lib/lxcfs($|/)|etc/(hostname|hosts|resolv\.conf)|mnt/pve/nas-unraid-01)$'
    node_exporter_fs_types_exclude: '^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|efivarfs|fusectl|hugetlbfs|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$'
