all:
  vars:
    domain: sevenos.fr
    ansible_user: root
    node_exporter_mount_points_exclude: '^/(proc($|/)|sys($|/)|run($|/)|tmp($|/)|mnt($|/)|media($|/)|dev($|/(pts|hugepages|mqueue))|var/lib/docker($|/)|var/lib/containers($|/)|var/lib/lxcfs($|/)|etc/(hostname|hosts|resolv\.conf)|mnt/pve/nas-unraid-01)$'
    node_exporter_fs_types_exclude: '^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|efivarfs|fusectl|hugetlbfs|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$'
  children:

    proxmox:
      children:

        proxmox_preprod:
          vars:
            env: preprod
          hosts:
            pprd-hpv-pmx-01:
              ansible_host: pprd-hpv-pmx-01.sevenos.fr

            pprd-hpv-pmx-02:
              ansible_host: pprd-hpv-pmx-02.sevenos.fr

            pprd-hpv-pmx-03:
              ansible_host: pprd-hpv-pmx-03.sevenos.fr

        proxmox_prod:
          vars:
            env: prod
          hosts:
            prod-hpv-pmx-01:
              ansible_host: prod-hpv-pmx-01.sevenos.fr
            
            prod-hpv-pmx-02:
              ansible_host: prod-hpv-pmx-02.sevenos.fr

            prod-hpv-pmx-03:
              ansible_host: prod-hpv-pmx-03.sevenos.fr

        proxmox_home:
          hosts:
            hpv-proxmox-01:
              ansible_host: hpv-proxmox-01.sevenos.fr
              env: home

        proxmox_remote:
          hosts:
            pve-remote-01:
              ansible_host: pve-remote-01.sevenos.fr
              env: remote

    pbs:
      hosts:
        pbs-local-01:
          ansible_host: pbs-local-01.sevenos.fr
          env: home
          platform: vm

        pbs-remote-01:
          ansible_host: pbs-remote-01.sevenos.fr
          env: remote
          platform: vm
    
    pdm:
      hosts:
        pdm-main-01:
          ansible_host: pdm-main-01.sevenos.fr
          env: home
          platform: vm
    
    vm:
      hosts:
        vm-mon-01:
          ansible_host: vm-mon-01.sevenos.fr
          ansible_user: admin
          env: home
          category: monitoring
        vm-docker-01:
          ansible_host: vm-docker-01.sevenos.fr
          env: home
          category: docker 
        vm-web-01:
          ansible_host: vm-web-01.sevenos.fr
          env: home
          category: reverse-proxy 
        vm-web-02:
          ansible_host: vm-web-02.sevenos.fr
          ansible_user: admin
          env: home
          category: reverse-proxy
        vm-ha-01:
          ansible_host: vm-ha-01.sevenos.fr
          env: home
          category: homeassistant
          metrics: 
            enabled: false
            install: false
        vm-db-01:
          ansible_host: vm-db-01.prod.sevenos.fr
          ansible_user: admin
          env: prod
          category: database

    nas:
      hosts:
        nas-unraid-01:
          ansible_host: nas-unraid-01.sevenos.fr
          env: home
          metrics:
            enabled: false
            install: false

    dns:
      vars:
        platform: baremetal
        metrics: 
          enabled: true
      hosts:
        pihole-deb-01:
          ansible_host: pihole-deb-01.sevenos.fr
          env: home
          category: dns

    gateway:
      vars:
        platform: vm
        metrics:
          enabled: true
      hosts:
        gw-main-01:
          ansible_host: gw-main-01.sevenos.fr
          env: home
          category: network
        gw-remote-01:
          ansible_host: gw-remote-01.sevenos.fr
          env: remote
          category: network