---
- name: Group hosts with metrics enabled
  hosts: all
  gather_facts: false
  tasks:
    - name: Add hosts to metrics group
      ansible.builtin.group_by:
        key: "metrics_enabled"
      when:
        - metrics is defined
        - metrics.enabled | default(false)
        - metrics.install | default(true)

- name: Install node_exporter on hosts
  hosts: metrics_enabled
  become: true
  gather_facts: true

  roles:
    - role: node_exporter
