version: '3'

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    user: root
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_HTTP_PORT=3000
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_DB=mydb
      - INFLUXDB_USER=admin
      - INFLUXDB_PASSWORD=password
    volumes:
      - /srv/docker/grafana/data:/var/lib/grafana
    networks:
      - grafana-net

  influxdb:
    image: influxdb
    container_name: influxdb
    user: root
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_INIT_MODE=setup
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
    volumes:
      - /srv/docker/influxdb/data:/var/lib/influxdb
    networks:
      - grafana-net

networks:
  grafana-net:
    driver: bridge

volumes:
  grafana-data:
  influxdb-data:
