version: "3.8"
services:
  trilium:
    image: triliumnext/notes:stable
    container_name: trilium-main
    hostname: dkr-trillium-01
    ports:
      - "8039:8080"
    volumes:
      - /srv/docker/trilium/data:/home/node/trilium-data
    restart: unless-stopped
